from setuptools import setup

setup(
    name='django-postpone-index',
    use_scm_version=True,
    python_requires='>=3.10',
    # build-time requirements are declared in pyproject.toml
    description='Postpone index creation to provide Zero Downtime Migration feature',
    author='Vsevolod Novikov',
    author_email='nnseva@gmail.com',
    url='https://github.com/nnseva/django-postpone-index',
    project_urls={
        'Source': 'https://github.com/nnseva/django-postpone-index',
        'Issues': 'https://github.com/nnseva/django-postpone-index/issues',
    },
    long_description=open('README.md', encoding='utf-8').read(),
    long_description_content_type='text/markdown',
    install_requires=['django2-postgres-backport', 'django-unlimited-char'],
    classifiers=[
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.10',
        'Programming Language :: Python :: 3.11',
        'Programming Language :: Python :: 3.12',
        'Programming Language :: Python :: 3.13',
        'Programming Language :: Python :: 3.14',
        'Programming Language :: Python :: 3.15',
        'Framework :: Django',
        'Framework :: Django :: 2.2',
        'Framework :: Django :: 3.0',
        'Framework :: Django :: 3.1',
        'Framework :: Django :: 3.2',
        'Framework :: Django :: 4.0',
        'Framework :: Django :: 4.1',
        'Framework :: Django :: 4.2',
        'Framework :: Django :: 5.0',
        'Framework :: Django :: 5.1',
        'Framework :: Django :: 5.2',
        'Development Status :: 4 - Beta',
        'Intended Audience :: Developers',
        'Topic :: Software Development :: Libraries',
    ],
    keywords=[
        'zero-downtime-migration',
        'django',
        'migration',
        'zero-downtime',
        'downtime',
        'postgres',
        'postgresql',
    ],
    license='LGPLv3',
    packages=[
        'postpone_index',
        'postpone_index/contrib',
        'postpone_index/contrib/postgres',
        'postpone_index/contrib/postgis',
        'postpone_index/management',
        'postpone_index/management/commands',
    ],
    package_data={
        'postpone_index': ['sql/start.sql'],
    },
)
