# Generated by Django 2.2.5 on 2026-01-30 10:40

from django.db import migrations, models

from postpone_index.migration_utils import PostponeIndexIgnoreMigrationMixin


class Migration(PostponeIndexIgnoreMigrationMixin, migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExplicitConstraint1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field1', models.CharField(max_length=10)),
                ('field2', models.CharField(max_length=10)),
                ('field3', models.CharField(max_length=10)),
            ],
        ),
    ]
