# Generated by Django 2.2.5 on 2026-01-30 10:44

from django.db import migrations, models

from postpone_index.migration_utils import PostponeIndexIgnoreMigrationMixin


class Migration(PostponeIndexIgnoreMigrationMixin, migrations.Migration):

    dependencies = [
        ('test_ignore_migration', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='explicitconstraint1',
            constraint=models.UniqueConstraint(condition=models.Q(('field1', '<empty>'), ('field2', '<empty>'), _negated=True), fields=('field1', 'field2'), name='ignore_explicit_constraint1_non_empty'),
        ),
    ]
