# Generated by Django 2.2 on 2026-02-04 09:15

import django
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExplicitConstraint1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field1', models.CharField(max_length=10)),
                ('field2', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ExplicitIndex1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field1', models.CharField(max_length=10)),
                ('field2', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UniqueField1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field1', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UniqueTogether1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field1', models.CharField(max_length=10)),
                ('field2', models.CharField(max_length=10)),
            ],
            options={
                'unique_together': {('field1', 'field2')},
            },
        ),
        migrations.AddIndex(
            model_name='explicitindex1',
            index=models.Index(fields=['field1', 'field2'], name='explicit_rename_index1_index'),
        ),
        migrations.AddConstraint(
            model_name='explicitconstraint1',
            constraint=models.UniqueConstraint(condition=models.Q(('field1', '<empty>'), ('field2', '<empty>'), _negated=True), fields=('field1', 'field2'), name='explicit_rename_constraint1_non_empty'),
        ),
    ]

    if django.VERSION < (5, 1):
        operations += [
            migrations.CreateModel(
                name='IndexTogether1',
                fields=[
                    ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                    ('field1', models.CharField(max_length=10)),
                    ('field2', models.CharField(max_length=10)),
                ],
                options={
                    'index_together': {('field1', 'field2')},
                },
            ),
        ]
