# Generated by Django 2.2 on 2026-02-04 09:17

import django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_fields_rename', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='explicitconstraint1',
            name='explicit_rename_constraint1_non_empty',
        ),
        migrations.RemoveIndex(
            model_name='explicitindex1',
            name='explicit_rename_index1_index',
        ),
        migrations.RenameField(
            model_name='explicitconstraint1',
            old_name='field1',
            new_name='renamed_field1',
        ),
        migrations.RenameField(
            model_name='explicitconstraint1',
            old_name='field2',
            new_name='renamed_field2',
        ),
        migrations.RenameField(
            model_name='explicitindex1',
            old_name='field1',
            new_name='renamed_field1',
        ),
        migrations.RenameField(
            model_name='explicitindex1',
            old_name='field2',
            new_name='renamed_field2',
        ),
        migrations.RenameField(
            model_name='uniquefield1',
            old_name='field1',
            new_name='renamed_field1',
        ),
        migrations.RenameField(
            model_name='uniquetogether1',
            old_name='field1',
            new_name='renamed_field1',
        ),
        migrations.RenameField(
            model_name='uniquetogether1',
            old_name='field2',
            new_name='renamed_field2',
        ),
        migrations.AlterUniqueTogether(
            name='uniquetogether1',
            unique_together={('renamed_field1', 'renamed_field2')},
        ),
        migrations.AddIndex(
            model_name='explicitindex1',
            index=models.Index(fields=['renamed_field1', 'renamed_field2'], name='explicit_rename_index1_index'),
        ),
        migrations.AddConstraint(
            model_name='explicitconstraint1',
            constraint=models.UniqueConstraint(condition=models.Q(('renamed_field1', '<empty>'), ('renamed_field2', '<empty>'), _negated=True), fields=('renamed_field1', 'renamed_field2'), name='explicit_rename_constraint1_non_empty'),
        ),
    ]

    if django.VERSION < (5, 1):
        operations += [
            migrations.RenameField(
                model_name='indextogether1',
                old_name='field1',
                new_name='renamed_field1',
            ),
            migrations.RenameField(
                model_name='indextogether1',
                old_name='field2',
                new_name='renamed_field2',
            ),
            migrations.AlterIndexTogether(
                name='indextogether1',
                index_together={('renamed_field1', 'renamed_field2')},
            ),
        ]
