# Generated by Django 2.2.5 on 2026-01-30 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_explicit_index', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='explicitindex1',
            index=models.Index(fields=['field1'], name='explicit_index1_index'),
        ),
    ]
