# Generated by Django 2.2.5 on 2026-01-30 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_explicit_index', '0002_auto_20260130_1044'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='explicitindex1',
            name='explicit_index1_index',
        ),
        migrations.AddIndex(
            model_name='explicitindex1',
            index=models.Index(fields=['field1', 'field2'], name='explicit_index1_index'),
        ),
    ]
