# Generated by Django 2.2 on 2026-02-04 10:37

import django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_model_rename', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExplicitIndex1',
            new_name='ExplicitIndex1Renamed',
        ),
        migrations.RenameModel(
            old_name='ExplicitConstraint1',
            new_name='ExplicitConstraint1Renamed',
        ),
        migrations.RenameModel(
            old_name='UniqueField1',
            new_name='UniqueField1Renamed',
        ),
        migrations.RenameModel(
            old_name='UniqueTogether1',
            new_name='UniqueTogether1Renamed',
        ),
    ]

    if django.VERSION < (5, 1):
        operations += [
            migrations.RenameModel(
                old_name='IndexTogether1',
                new_name='IndexTogether1Renamed',
            ),
        ]
