# Generated by Django 2.2.5 on 2026-01-30 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_explicit_constraint', '0002_auto_20260130_1044'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='explicitconstraint1',
            name='explicit_constraint1_non_empty',
        ),
        migrations.AddConstraint(
            model_name='explicitconstraint1',
            constraint=models.UniqueConstraint(condition=models.Q(('field1', '<empty>'), ('field2', '<empty>'), ('field3', '<empty>'), _negated=True), fields=('field1', 'field2', 'field3'), name='explicit_constraint1_non_empty'),
        ),
    ]
