# Generated by Django 2.2.5 on 2026-02-02 10:55

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GisIndex1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mpoint', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
    ]
