# Generated by Django 2.2.5 on 2026-02-02 11:55

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.linestring
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_gis_index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gisindex1',
            name='mline',
            field=django.contrib.gis.db.models.fields.LineStringField(default=django.contrib.gis.geos.linestring.LineString(((0, 0), (0, 0))), srid=4326),
        ),
    ]
