# Generated by Django 2.2.5 on 2026-02-02 11:56

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.collections
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_gis_index', '0002_gisindex1_mline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gisindex1',
            name='mpoint',
        ),
        migrations.AddField(
            model_name='gisindex1',
            name='mpoly',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(db_index=True, default=django.contrib.gis.geos.collections.MultiPolygon(), srid=4326),
        ),
    ]
