# Generated by Django 2.2.5 on 2026-01-30 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UniqueTogether2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field1', models.CharField(max_length=10)),
                ('field2', models.CharField(max_length=10)),
                ('field3', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UniqueTogether3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field1', models.CharField(db_column='test_field1', max_length=10)),
                ('field2', models.CharField(db_column='test_field2', max_length=10)),
                ('field3', models.CharField(db_column='test_field3', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UniqueTogether1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field1', models.CharField(max_length=10)),
                ('field2', models.CharField(max_length=10)),
            ],
            options={
                'unique_together': {('field1', 'field2')},
            },
        ),
    ]
