# Generated by Django 2.2.5 on 2026-01-30 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_unique_together', '0002_auto_20260130_1044'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='uniquetogether2',
            unique_together={('field1', 'field2', 'field3')},
        ),
        migrations.AlterUniqueTogether(
            name='uniquetogether3',
            unique_together={('field1', 'field2', 'field3')},
        ),
    ]
