# Generated by Django 2.2.5 on 2026-01-30 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndexedField1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field1', models.CharField(db_index=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='IndexedField2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field1', models.CharField(max_length=10)),
                ('field2', models.CharField(db_index=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UniqueField1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field1', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UniqueField2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field1', models.CharField(max_length=10)),
                ('field2', models.CharField(max_length=10, unique=True)),
            ],
        ),
    ]
