# Generated by Django 2.2.5 on 2026-01-30 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_fields', '0002_auto_20260130_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexedfield1',
            name='field1',
            field=models.CharField(db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='indexedfield2',
            name='field1',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='uniquefield1',
            name='field1',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='uniquefield2',
            name='field1',
            field=models.CharField(max_length=10),
        ),
    ]
